source:
    url: http://tvheadend:9981/stream/channel/{id}
    reconnectTimeout: 10
ffmpeg:
    path: '/usr/bin/ffmpeg'
    profiles:
        -
            alias: "aac"
            parameters: "-c:a:0 aac -b:a 320k -c:v copy -threads 0 -f mpegts"
        -
            alias: "raw"
            parameters: "-c:a copy -c:v copy -threads 0 -f mpegts"
        -
            alias: "720p"
            parameters: "-c:a:0 aac -b:a 320k -c:v libx264 -tune zerolatency -g 10 -vprofile high -level 4.0 -crf 18 -movflags +faststart -bufsize 15000k -maxrate 10000k  -preset fast -vf \"scale=-1:720,yadif=0\" -threads 0 -f mpegts"
        -
            alias: "1080p"
            parameters:  "-c:a:0 aac -b:a 320k -c:v libx264 -tune zerolatency -g 10 -vprofile high -level 4.1 -crf 21 -movflags +faststart -bufsize 15000k -maxrate 10000k  -preset fast -vf yadif=0 -threads 0 -f mpegts"
    
    hls:
        tempPath: "/tmp"
        parameters: "-vcodec copy -acodec copy   -flags -global_header  -avoid_negative_ts disabled -map_metadata -1 -start_at_zero -copyts -flags -global_header -vsync cfr -y -nostats -f hls -hls_time 1 -hls_list_size 20 -hls_wrap 30"
        timeout: 120
        
buffers:
    chunkSize: 1048576
    broadcastBufferSize: 52428800
